name: color_picker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  color:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  uuid:
  flutter_colorpicker:
  fl_toast:
  font_awesome_flutter:
  image_picker:
  path:
  provider:
  shared_preferences:
  hive:
  hive_flutter:
  url_launcher:
  url_strategy:
  window_manager:
  firebase_crashlytics:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons_maker: ^0.10.1
  flutter_lints: ^1.0.4


flutter:


  uses-material-design: true

  assets:
    - assets/


flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/icon.png"



dependency_overrides:
  platform: ^3.1.0




