name: color_picker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  color: ^3.0.0
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  uuid:
  flutter_colorpicker: ^1.0.3
  fl_toast: ^3.1.0
  font_awesome_flutter: ^10.0.0
  image_picker: 0.8.4+11
  path: ^1.8.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  window_manager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.1
  flutter_launcher_icons_maker: ^0.10.1
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/


flutter_native_splash:
  # FF9800
  color: "#FF9800"
  image: assets/icon.png

# To generate the icons, run `flutter pub run flutter_launcher_icons_maker:main` under
# the root directory
flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/icon.png"

dependency_overrides:
  platform: ^3.1.0




