// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfyCcVWzICnWd3HzH9eb22RN0pCWi6tYM',
    appId: '1:645970464567:web:2083d214924dd2a082d4b2',
    messagingSenderId: '645970464567',
    projectId: 'todo-firestore-d6bd0',
    authDomain: 'todo-firestore-d6bd0.firebaseapp.com',
    storageBucket: 'todo-firestore-d6bd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkGfWunG50EYUQeWuy3HtzR9rH-YryBNw',
    appId: '1:645970464567:android:d03b675aaa1a50f082d4b2',
    messagingSenderId: '645970464567',
    projectId: 'todo-firestore-d6bd0',
    storageBucket: 'todo-firestore-d6bd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9M8SuGIADxyFGlqXMSmNXQQDeUdCvZLA',
    appId: '1:645970464567:ios:0b3090b4fc6075d782d4b2',
    messagingSenderId: '645970464567',
    projectId: 'todo-firestore-d6bd0',
    storageBucket: 'todo-firestore-d6bd0.appspot.com',
    androidClientId: '645970464567-mldr122cmm7hh9kgetqu1s31clm5gdo0.apps.googleusercontent.com',
    iosClientId: '645970464567-ggcgrk7eii0tlp5pv0fc14i7nlmpeoi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirestore',
  );
}
